root: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
plugins:
  - prettier
  - simple-import-sort
env:
  es6: true
  browser: true
  amd: true
  node: true
extends:
  - eslint:recommended
globals:
  sigma: readonly
rules:
  no-template-curly-in-string: error
  prefer-template: error
  prettier/prettier: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: off
  sort-keys: error
overrides:
  - files: [ "**/*.ts" ]
    parser: '@typescript-eslint/parser'
    parserOptions:
      tsconfigRootDir: .
      project:
        - ./tsconfig.json
        - ./tsconfig.worker.json
    plugins:
      - '@typescript-eslint'
      - simple-import-sort
      - prettier
    env:
      es6: true
      browser: true
      amd: true
      node: true
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - prettier/@typescript-eslint
    rules:
      '@typescript-eslint/member-ordering':
        - error
        - default:
            - signature
            - field
            - method
          classes:
            - public-static-field
            - public-instance-method
      '@typescript-eslint/no-implied-eval': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/no-unsafe-call': off
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unsafe-return': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/unbound-method': off
      simple-import-sort/exports: error
      simple-import-sort/imports: error
      sort-keys: error
