id: AND operation
inputs:
  - normalizerRef: boolean
  - normalizerRef: boolean
hiddenLayersCounts: [ 3 ]
outputs:
  - normalizerRef: boolean
strategy:
  id: logistic
  options:
    minWeight: -1000
    maxWeight: 1000
training:
  expectedMaxIterations: 100
  learningRate: 0.2
  usecases:
    - inputs: [ false, false ]
      outputs: false
    - inputs: [ false, true ]
      outputs: false
    - inputs: [ true, false ]
      outputs: false
    - inputs: [ true, true ]
      outputs: true
